// ESLint configuration for scitex-ui's TypeScript surface.
//
// WHY THIS FILE EXISTS. This repo ships 272 TypeScript files and had NO LINTER
// AT ALL. `npm run typecheck` runs `tsc --noEmit`, which checks TYPES — it does
// not check unused bindings, no-op expressions, `this` aliasing, or `any` at
// boundaries. So an entire class of defect had nothing looking for it.
//
// The absence was invisible for a second reason: the fleet's post-write lint
// hook shells `eslint`, eslint exits with a config error, and the hook reports
// a BLOCKING failure with no message. Every `.ts` write in this repo produced
// an empty error that reads exactly like a lint failure and was in fact a
// could-not-run. (Carded separately — the hook's swallowed banner is the
// operator's to fix; this file removes the condition that triggers it here.)
//
// ═══════════════════════════════════════════════════════════════════════════
// THIS CHANGE IS PURELY ADDITIVE. NO SOURCE FILE IS EDITED.
// ═══════════════════════════════════════════════════════════════════════════
//
// Every rule below is ON and gates NEW code. Every existing violation is named
// in an exemption block with its count. That is §2's grandfathering rule done
// as prescribed — "exempt rules ONE AT A TIME, in a config file, each with a
// written reason: reviewable, greppable, and individually revisitable" — and
// explicitly NOT "a flag that silences the whole run".
//
// The alternative was to fix 166 violations in the same change. Rejected: the
// `no-explicit-any` half is design work (choosing real types for untyped
// vendor surfaces), not mechanical, and a config change plus 40 files of type
// edits would produce one PR with two candidate causes for anything it broke.
// Burn-down is separate, incremental, and safe.
//
// MEASURED BEFORE CHOOSING ANY RULE, on 2026-09-03, against
// typescript-eslint's `recommended`:
//
//     259 files linted, 54 with hits, 166 violations
//
//      127  @typescript-eslint/no-explicit-any
//       29  @typescript-eslint/no-unused-vars
//        6  @typescript-eslint/no-unused-expressions
//        3  prefer-const
//        1  @typescript-eslint/no-this-alias
//
// One rule is 76% of the total, so it alone decided whether this was a tidy
// change or a 127-entry grandfather list. Measuring WHERE those 127 live is
// what made the difference: 98 of them (77%) sit in five directories that wrap
// untyped third-party surfaces, where `any` is frequently the honest type.
// Those get a DIRECTORY exemption with a reason. The remaining 29, across 16
// files, are named individually.

import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

/** Directories whose job is to wrap an untyped or dynamically-typed vendor API. */
const VENDOR_BOUNDARIES = [
  // 42 violations. monaco-editor is a PEER dependency the adopter loads; large
  // parts of its API surface are typed loosely or reached through a loader.
  "src/scitex_ui/static/scitex_ui/ts/app/monaco-editor/**",
  // 14 across both viewers. pdfjs-dist and mermaid are peer dependencies.
  "src/scitex_ui/static/scitex_ui/ts/app/media-viewer/**",
  "src/scitex_ui/static/scitex_ui/ts/shell/viewer/**",
  // 7. Wraps the terminal emulator.
  "src/scitex_ui/static/scitex_ui/ts/shell/terminal/**",
  // 23. Walks ARBITRARY DOM nodes and console payloads by design — the values
  // genuinely have no static type, which is the one case where `any` is not a
  // shortcut but a description.
  "src/scitex_ui/static/scitex_ui/ts/utils/_element-inspector/**",
];

export default tseslint.config(
  {
    ignores: [
      // Generated bundles. Editing them is already forbidden by their banner;
      // linting them would report defects nobody can fix in place.
      "src/scitex_ui/static/scitex_ui/js/**",
      // Vendored Sphinx assets — third-party, regenerated by the docs build.
      "src/scitex_ui/_sphinx_html/**",
      "node_modules/**",
    ],
  },
  {
    files: [
      "src/scitex_ui/static/scitex_ui/ts/**/*.ts",
      "src/scitex_ui/static/scitex_ui/react/**/*.ts",
      "src/scitex_ui/static/scitex_ui/react/**/*.tsx",
    ],
    extends: [tseslint.configs.recommended],
  },

  {
    // REACT HOOKS. This plugin is here because the SOURCE ALREADY ASSUMED IT:
    // five inline `eslint-disable-...-line react-hooks/exhaustive-deps`
    // comments exist across DataTable.tsx and PdfViewer.tsx, written by
    // whoever built those components. With no linter configured they have been
    // INERT for their entire life — and worse, eslint 9 treats a disable
    // comment naming an unknown rule as an ERROR, so adding any config at all
    // without this plugin turns five dormant comments into five hard failures.
    //
    // That is how I first met them: I counted eslint's `ruleId` field and read
    // "react-hooks/exhaustive-deps" five times, without reading the `message`
    // beside it — which said "Definition for rule was not found". They were
    // never violations. Installing the plugin makes the author's original
    // suppressions mean what they were written to mean.
    files: ["src/scitex_ui/static/scitex_ui/react/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      // ERROR, not "warn". A warning nothing gates on is a check that cannot
      // fail — §2 — and it would rot into background noise exactly like the
      // five dead disable comments below it did. The one existing violation is
      // named instead.
      "react-hooks/exhaustive-deps": "error",
    },
  },
  {
    // ONE genuine exhaustive-deps finding, surfaced by installing the plugin:
    // an effect whose dependency list omits a value it reads. Exempted rather
    // than fixed because "just add the missing dep" is the one wrong move here
    // — a dependency added blindly to a resize handler is how you get a render
    // loop, and this file drives panel layout. It needs reading, not a
    // mechanical fix, and this PR edits no source.
    files: ["src/scitex_ui/static/scitex_ui/react/app/usePanelResize.ts"], // 1
    rules: { "react-hooks/exhaustive-deps": "off" },
  },

  // ── EXEMPTIONS ────────────────────────────────────────────────────────────
  // Each block names ONE rule and the exact files that violate it today, with
  // counts. A file leaving a list is the burn-down; a file being ADDED to one
  // should be refused in review, because the rule is on for new code.

  {
    // Vendor boundaries: `any` is often the correct type here, and forcing a
    // fabricated interface onto a peer dependency's surface would be worse
    // than honest — it would assert a shape we do not control and cannot keep
    // in step with their releases.
    files: VENDOR_BOUNDARIES,
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },
  {
    // The 29-violation TAIL, outside any vendor boundary. These are OUR types
    // to write, and each is real debt rather than a boundary. Listed
    // individually so the list shrinks visibly.
    files: [
      "src/scitex_ui/static/scitex_ui/ts/shell/auto-response/_AutoResponseManager.ts", // 4
      "src/scitex_ui/static/scitex_ui/ts/shell/auto-response/_auto-response-config.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/auto-response/_claude-state-detector.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/chat/_markdown-render.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/keyboard-shortcuts/_KeyboardShortcuts.ts", // 4
      "src/scitex_ui/static/scitex_ui/ts/shell/resizer/_drag-handler.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/resizer/index.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/WorkspaceFilesTree.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_TreeState.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/ClipboardHandler.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/DragState.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/FileActions.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/GitActions.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/TreeMessageHandler.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/types.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/utils/element-inspector.ts", // 4
    ],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },
  {
    // 29 unused bindings. Mechanical to fix (delete, or prefix with `_` where
    // the signature must keep the parameter) but 20 files of edits, which
    // belongs in its own change rather than riding along with the config.
    files: [
      // Found only after .tsx entered scope — the original measurement scanned
      // `**/*.ts` and never linted a single .tsx file, so the whole React
      // surface was outside the population the rest of this list was built
      // from. Recorded here rather than quietly appended.
      "src/scitex_ui/static/scitex_ui/react/app/file-browser/FileBrowser.tsx", // 1
      "src/scitex_ui/static/scitex_ui/ts/app/data-table/DataTableManager.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/app/data-table/_TableEditing.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/app/data-table/_TableRendering.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/app/monaco-editor/_MonacoLoader.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/file-tree/types.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/repo-monitor/_RepoMonitorClient.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/resizer/_base.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/resizer/_cascade.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/types.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/viewer/_PdfViewer.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/viewer/_ViewerManager.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_TreeRenderer.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/PathNavigator.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/SelectionHandler.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/UndoRedoHandler.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/utils/_element-inspector/_console-collector.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/utils/_element-inspector/_debug-info-collector.ts", // 3
      "src/scitex_ui/static/scitex_ui/ts/utils/_element-inspector/_element-scanner.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/utils/_element-inspector/_page-structure-exporter.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/utils/context-zoom.ts", // 1
    ],
    rules: { "@typescript-eslint/no-unused-vars": "off" },
  },
  {
    // 6 no-op expressions. Each needs reading before touching: a bare
    // `foo.bar;` is usually dead, but is occasionally a deliberate property
    // access for its getter side effect, and deleting that breaks silently.
    files: [
      "src/scitex_ui/static/scitex_ui/ts/app/combobox/_Combobox.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/app/dropdown/_Dropdown.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/resizer/_Resizer.ts", // 1
      "src/scitex_ui/static/scitex_ui/ts/shell/resizer/_base.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/workspace-files-tree/_handlers/ContextMenuHandler.ts", // 1
    ],
    rules: { "@typescript-eslint/no-unused-expressions": "off" },
  },
  {
    // 3 `let` that are never reassigned. Trivial, and still not fixed here,
    // because a config PR that also edits source is a config PR you cannot
    // revert cleanly.
    files: [
      "src/scitex_ui/static/scitex_ui/react/app/data-table/hooks/useDataReducer.ts", // 2
      "src/scitex_ui/static/scitex_ui/ts/shell/resizer/_Resizer.ts", // 1
    ],
    rules: { "prefer-const": "off" },
  },
  {
    // 1 `const self = this`. Inside the element inspector, which is already
    // exempted from no-explicit-any for the same underlying reason: it walks
    // arbitrary runtime structures.
    files: [
      "src/scitex_ui/static/scitex_ui/ts/utils/_element-inspector/_console-collector.ts", // 1
    ],
    rules: { "@typescript-eslint/no-this-alias": "off" },
  },
);
