"""Cross-package import gate (PS-140) for scitex-ui.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.

generated-by: scitex-dev 0.59.0

A GATE NOBODY CAN DATE IS A CLAIM ABOUT AN UNKNOWN PAST. This
list is a snapshot of the cross-package imports as they stood
when the stamp above was written; it does not update itself, and
a stale copy looks exactly like a current one. Measured
2026-08-16: 17 gates across the fleet carried NO stamp and named
a generator that never existed as a command -- the real writer
was a one-shot script since deleted -- so the only way to tell a
fossil from a live gate was a filesystem sweep of mtimes. The
same disease had already been found in the audit gate (68 of 70
still calling audit_all_for_package() with no path=), and the
same cure applies: say which version wrote you.

Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-ui --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).

Hand-written cases go BELOW the second sentinel. Everything there
is preserved byte-identically across regeneration; everything
between the sentinels is overwritten.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex_dev._cli._completion',
    'scitex_dev.cli',
    'scitex_dev.ecosystem',
    'scitex_dev.linter._rules._base',
    'scitex_static',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-ui's declared cross-package dependency must succeed.

    SKIP ON THE ROOT, HARD-IMPORT THE FULL PATH. The two steps answer two
    different questions and collapsing them is what made this gate silent:

    ``pytest.importorskip("scitex_dev.linter._rules._base")`` skips whenever
    ANY part of that path is missing — including when the peer IS installed and
    the SUBMODULE was renamed. That is precisely the case the module docstring
    above promises to catch ("Module installed BUT import fails … → test FAILS
    loudly"), and the gate reported green through it instead.

    So the root import decides "is the peer here at all?" — a legitimate skip on
    a lean install where the peer is an optional extra. The full import then
    decides "does the path we actually reference still exist?" — never a skip,
    always a failure.

    Do NOT simplify this back to a single hard import: that breaks the lean
    install the skip exists for. The two lines are two questions.
    """
    # Arrange
    root = module_name.split(".")[0]
    # Act
    pytest.importorskip(root)
    mod = importlib.import_module(module_name)
    # Assert
    assert mod is not None
