#!/usr/bin/env python3
"""Guards that the generated CSS bundles actually import everything that ships.

`all.css` / `app.css` / `shell.css` are the only entry points consumers load.
They are auto-generated by `css/_build-index.ts`, which scans the directory
correctly — but regenerating is a MANUAL step, and nothing enforced it. Two
stylesheets (badge.css, combobox.css) therefore shipped inside the package
while being imported by no entry point at all: an app following the
documentation got the class name and no styling, and nothing failed.

That is the same defect class as the unregistered components 0.9.0 fixed, one
layer down — the artifact is present, the wiring that surfaces it is missing,
and the failure is silent on both sides. So this recomputes the expected
import set from the filesystem and compares, which catches the NEXT new
stylesheet too, not just the two that were found by an adopter.

Mirrors `_build-index.ts`: files starting with `_` are skipped, the three
generated bundles never import themselves, paths are `./`-prefixed and sorted.
"""

from __future__ import annotations

import re

import pytest

from tests._checkout import css_dir

_CSS_DIR = css_dir()
_GENERATED = ("all.css", "shell.css", "app.css")

# name -> subdirectories scanned, matching buildIndex(...) calls in _build-index.ts
_BUNDLES = {
    "shell.css": ("shell", "primitives"),
    "app.css": ("app",),
    "all.css": None,  # whole tree
}


def _shipped_css(roots) -> set[str]:
    """Every stylesheet a bundle should import, as './'-prefixed relpaths."""
    dirs = [_CSS_DIR] if roots is None else [_CSS_DIR / r for r in roots]
    found: set[str] = set()
    for d in dirs:
        if not d.is_dir():
            continue
        for path in d.rglob("*.css"):
            if path.name in _GENERATED:
                continue
            rel = path.relative_to(_CSS_DIR)
            if any(part.startswith("_") for part in rel.parts):
                continue
            found.add("./" + rel.as_posix())
    return found


def _imported_by(bundle: str) -> set[str]:
    text = (_CSS_DIR / bundle).read_text()
    return set(re.findall(r'@import\s+"([^"]+)"', text))


class TestGeneratedBundlesAreCurrent:
    @pytest.mark.parametrize("bundle", sorted(_BUNDLES))
    def test_every_shipped_stylesheet_is_imported(self, bundle):
        # Arrange
        expected = _shipped_css(_BUNDLES[bundle])
        # Act
        missing = sorted(expected - _imported_by(bundle))
        # Assert
        assert not missing, (
            f"{bundle} does not import {missing}; those stylesheets ship in the "
            f"package but reach no page. Regenerate: npx tsx css/_build-index.ts"
        )

    @pytest.mark.parametrize("bundle", sorted(_BUNDLES))
    def test_no_import_points_at_a_missing_file(self, bundle):
        # Arrange
        imported = _imported_by(bundle)
        # Act
        dangling = sorted(i for i in imported if not (_CSS_DIR / i).is_file())
        # Assert
        assert not dangling, (
            f"{bundle} imports {dangling}, which do not ship; the bundle would "
            f"fail to resolve at runtime"
        )

    @pytest.mark.parametrize("bundle", sorted(_BUNDLES))
    def test_bundle_is_not_empty(self, bundle):
        # Arrange
        # Act
        count = len(_imported_by(bundle))
        # Assert
        assert count > 0, f"{bundle} imports nothing; guard would be vacuous"
