"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

DO NOT regenerate this file blindly. The generator emits
`audit_all_for_package('scitex-ui')` with no `path=`, which the
helper's own docstring forbids in capitals: without it the audit
resolves a tree by cwd/import guess and "grades source that is NOT
the commit under test while reporting a confident pass/fail".
Measured by scitex-hpc 2026-07-29 — their gate audited base develop
(HEAD 5532a0e) while the worktree under test was at c7d64bd, and it
disclosed that only in an INFO line. If you re-run the generator,
re-apply the `path=` anchor below.

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil
from pathlib import Path

import pytest

# The checkout this test file lives in — by construction the tree pytest is
# running against. Anchored on __file__ rather than the cwd, because the cwd
# is not a stable thing: on a CI runner with no per-job isolation it can be
# another job's tree or an older commit of this one.
#
# tests/develop/test_audit.py -> parents[2] is the repo root. (scitex-dev's
# docstring shows parents[1], which is right for tests/test_audit.py; this
# gate sits one level deeper.)
_REPO_ROOT = Path(__file__).resolve().parents[2]


def test_audit_gate_anchors_on_this_checkout():
    # Arrange — guards the anchor itself. If _REPO_ROOT ever stops pointing at
    # the real root, the audit below silently grades some other tree and still
    # reports a confident pass/fail.
    marker = _REPO_ROOT / "pyproject.toml"
    # Act
    found = marker.is_file()
    # Assert
    assert found, f"_REPO_ROOT resolved to {_REPO_ROOT}, which has no pyproject.toml"


def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package("scitex-ui", path=_REPO_ROOT)
